// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jiffoibtlbemwdlohwjo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImppZmZvaWJ0bGJlbXdkbG9od2pvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ0NjQ1ODYsImV4cCI6MjA2MDA0MDU4Nn0.zEhh7ewtpEHaBR2c1azndg-4-itQQuCaPli5Z-IkTvs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);